### ISSUE TITLE
Unable to delete failed deployment

### ISSUE THREAD

**Issue by Mike-ops273** [diploi/nextjs-postgresql-template#1]
Delete Deployment request has been hanging for over 20 minutes. Now clicking on the deployment from the Deployments menu doesn't do anything. 

<img width="1073" alt="stuck" src="https://github.com/diploi/nextjs-postgresql-template/assets/73826014/d123d492-2a98-4d9e-be93-33ca7d665e47">

This causes a problem when pressing "Delete Project" because Diploi is still waiting for the Deployment to be done deleting. 

<img width="1068" alt="Screenshot 2023-05-11 at 9 23 20" src="https://github.com/diploi/nextjs-postgresql-template/assets/73826014/c1117bdb-9c67-4fd9-a131-2581aa96ad7a">

I tried refreshing the page and logging out but it seems the delete request is still pending. 
Also connection to the Core has been lost. 

<img width="767" alt="core-connection-lost" src="https://github.com/diploi/nextjs-postgresql-template/assets/73826014/918238e7-4706-4119-aabb-228e7b3f10be">

**Comment by MarcusAhlfors** [comment]
I think the issue is that you have to have the core running before it can complete the deletion, could that be the case. Try starting the core?

**Comment by Mike-ops273** [comment]
Ok nice, it worked when I turned the Core back on.
